### ISSUE TITLE
参考教程安装webots的版本问题

### ISSUE THREAD

**Issue by jiuyewxy** [CubeSugarCheese/plct-report#1]
参考教程安装后在安装目录下sh运行webots，显示是2024版本

运行launch文件时会提示需要webots 2023版本，选自动安装后会安装（若没有事先源码构建，无法自动安装webots 2023）

你在测试时有遇到这个问题么？

根据官方教程设置路径后倒是可launch文件启动2024版本

**Comment by CubeSugarCheese** [comment]
launch自动下载的是最新的稳定版本，从源码安装的是nightly版本。
[Webots release页面](https://github.com/cyberbotics/webots/releases)
我之后改一下文档说明一下
