### ISSUE TITLE
补充webots引入包相关检查点表格

### ISSUE THREAD

**Issue by jiuyewxy** [CubeSugarCheese/plct-report#2]
<img width="1118" alt="80fcfab4bd6a4d757e2dbeae29f19f5" src="https://github.com/user-attachments/assets/c01c1e4b-011b-4fea-a6c1-ac4661e1e6e3">

参考上面表格内容，将webots的对应表格填写后补充到你之前的文档上，或者单开一个report

**Comment by CubeSugarCheese** [comment]
已经补充完毕
